import type { LevelDef } from "../level-types";

export const SILT_FLATS: LevelDef = {
  id: "silt-flats",
  chapter: "VIII",
  title: "The Silt Flats",
  tagline: "Down here the ground drinks every sound — yours included.",
  act: 2,
  abilities: ["deepListen"],
  grants: ["deepListen"],
  map: [
    "################################################",
    "################################################",
    "############:::::oooooo::.....::oooooo#:::::####",
    "##########:::::::oooooo::..*..::oooooo:::::::###",
    "##########:::::::oooooo::.....::oooooo:::::::###",
    "##########:::::::oooooo::::b::::.d.ooo:::::::###",
    "##........:::::::oooooo:::::::::oooooo:::::e:###",
    "##........:::::::oooooo::::::oo:oooooo:::U:::###",
    "##........:::::a:oooooo::::::oo:oooooo::.....###",
    "##..@....h:::::::..dV..:::::::::oooooo::.....###",
    "##........:::::::oooooo:::::::::oooooo::..X..###",
    "##........:::k:::oooooo:::::::::oooooo::.....###",
    "##........::::oo:oooooo::oo:::::oooooo::.....###",
    "##########::::oo:oooooo::oo:::::oooooo:c:::::###",
    "##########:.m...:oooooo:::::::::...d..:::::::###",
    "##########:.....:oooooo:::::::::oooooo:::::::###",
    "##########:..*..:oooooo:::::::::oooooo:::::::###",
    "##########:.....:oooooooo:::::::oooooo:::::::###",
    "##########oo:::::oooooooo:::::##oooooo:::::#####",
    "################################################",
    "################################################",
  ],
  legend: {
    V: { kind: "warden", route: "ab" },
    U: { kind: "warden", route: "ce" },
    a: { kind: "waypoint" },
    b: { kind: "waypoint" },
    c: { kind: "waypoint" },
    e: { kind: "waypoint" },
    h: {
      kind: "hint",
      text: "Hunters walk the flats. Stand still, and let their own clicking — and the dripping water — show you the way.",
      radius: 1.6,
    },
    k: { kind: "hint", text: "The silt swallows your footsteps — and your voice along with them.", radius: 1.6 },
  },
};

export const WHAT_WALKS_BELOW: LevelDef = {
  id: "what-walks-below",
  chapter: "IX",
  title: "What Walks Below",
  tagline: "These have no ears at all. They listen with their feet.",
  act: 2,
  abilities: ["deepListen"],
  map: [
    "################################################",
    "#################################.....##########",
    "#################################..X..##########",
    "#################################.....##########",
    "#################################.....##########",
    "#############:#####:########:#####..#####:######",
    "########.....................................###",
    "########*..c..................U............e.###",
    "########.....................................###",
    "########.....................................###",
    "########################~~######################",
    "########################~~######################",
    "########################~~######################",
    "########################~k######################",
    "########################~~######################",
    "##....m.################~~######################",
    "##.......................................#######",
    "##..@.....a.............T.............b.*#######",
    "##......h................................#######",
    "##......######:######:#######:#####:############",
    "################################################",
    "################################################",
    "################################################",
  ],
  legend: {
    T: { kind: "warden", creature: "tremor", route: "ab" },
    U: { kind: "warden", creature: "tremor", route: "ce" },
    a: { kind: "waypoint" },
    b: { kind: "waypoint" },
    c: { kind: "waypoint" },
    e: { kind: "waypoint" },
    h: {
      kind: "hint",
      text: "Something heavy walks these halls. It is deaf — call as often as you like — but it feels every step. When it comes close, be still.",
      radius: 1.8,
    },
    k: { kind: "hint", text: "Water carries every step, however careful. Wade only when the ground around you is quiet.", radius: 1.6 },
  },
};

export const BREATHING_HALLS: LevelDef = {
  id: "breathing-halls",
  chapter: "X",
  title: "The Breathing Halls",
  tagline: "The dark breathes here, always in the same direction.",
  act: 2,
  abilities: ["deepListen", "focus"],
  grants: ["focus"],
  map: [
    "##############################################",
    "##############################################",
    "##.......#####oooooooooooo####################",
    "##............oooooooooooo...#################",
    "##..@.......a.o>>>>>>>>>>o.A.#################",
    "##............oooooooooooo...#################",
    "##.......#####oooooooooooo####################",
    "##.......#####################################",
    "##.......#####oooooooooooooooooooooUooo#######",
    "#####1########ooo>>>>>>>>>oooooo>>>>>*o#######",
    "####...#######ooo>>>>>>>>>oooooo>>>>>>o#######",
    "###..........#ooo>>ooooo>>oooooo>>o>>>o#######",
    "###..........#ooo>>ooooo>>oooooo>>o>>>o.....##",
    "###.....b.B..2>>>>>ooooo>>oooooo>>oq>>......##",
    "###..........#>>>>>o>>>>>>oooooo>>oo>>...X..##",
    "###..........#oooooooooo>>oooVoo>>oo>>o.....##",
    "##############oooooooooo>>ooo>oo>>ooooo.....##",
    "##############oooooooooo>>>>>>>>>>ooooo#######",
    "##############oooooooooo>>>>>>>>>>ooooo#######",
    "##############ooooooooooooooo>ooooooooo#######",
    "##############ooooooooooooooopooooooooo#######",
    "##############ooooooooooooooooooooooooo#######",
    "##############################################",
    "##############################################",
    "##############################################",
  ],
  legend: {
    A: { kind: "bell", group: 1, threshold: 0.22 },
    B: { kind: "bell", group: 2, threshold: 1.4 },
    V: { kind: "warden", route: "p" },
    U: { kind: "warden", route: "q" },
    p: { kind: "waypoint" },
    q: { kind: "waypoint" },
    a: {
      kind: "hint",
      text: "The wind runs along that ridge, away from you. A full call that rides it carries much further than in still air.",
      radius: 1.8,
    },
    b: {
      kind: "hint",
      text: "This bell is too heavy for any ordinary call. Hold [Q] and aim with the pointer: a focused call strikes harder, and barely carries to anything that listens.",
      radius: 2,
    },
  },
};
