import type { Ability, LevelDef } from "../level-types";

/** Act III keeps the whole kit of Act II. */
const KIT: readonly Ability[] = ["deepListen", "focus", "lureStone", "muffle"];

export const THE_SLUICES: LevelDef = {
  id: "the-sluices",
  chapter: "XIX",
  title: "The Sluices",
  tagline: "Water carries every note — and every step. Silt keeps both.",
  act: 3,
  abilities: KIT,
  introduces: ["sluices"],
  stones: 1,
  map: [
    "############################",
    "##################..X.######",
    "##################....######",
    "###################hh#######",
    "##........bbbbbbo......#####",
    "##....g..obbbbbbo......#####",
    "##.......obbbbbbo....r.#####",
    "##.....c.obbbbbbo..T...#####",
    "##.......oUbbbbuo......#####",
    "##.......obbbbbbo......#####",
    "##.......obbbbbbo......#####",
    "##..@....obbbbb*o......#####",
    "##.......obbbbbbo......#####",
    "##.......obbbbbbo......#####",
    "##.......oybbbbYo......#####",
    "##.......obbbbbbo......#####",
    "##..f....obbbbbbo......#####",
    "##.......obbbbbbo....V.#####",
    "##S......obbbbbbo......#####",
    "##.......obbbbbb.......#####",
    "############################",
    "############################",
  ],
  legend: {
    c: { kind: "key", note: 1 },
    h: { kind: "glass", notes: [1] },
    T: { kind: "crystal", note: 1 },
    b: { kind: "basin", group: 1, flooded: false },
    S: { kind: "bell", group: 1, toggle: true },
    U: { kind: "warden", creature: "tremor", route: "u" },
    u: { kind: "waypoint" },
    Y: { kind: "warden", creature: "tremor", route: "y" },
    y: { kind: "waypoint" },
    V: { kind: "warden", route: "r" },
    r: { kind: "waypoint" },
    f: { kind: "hint", text: "A sluice bell. Each time it rings, the channel floods — or drains.", radius: 1.8 },
    g: {
      kind: "hint",
      text: "The Gate's glass wants a C, and a crystal across the channel would carry it — but drained silt swallows every sound that crosses it.",
      radius: 1.8,
    },
  },
};

export const THE_METRONOME: LevelDef = {
  id: "the-metronome",
  chapter: "XX",
  title: "The Metronome",
  tagline: "It keeps the Instrument's time. Keep it too.",
  act: 3,
  abilities: KIT,
  introduces: ["metronome"],
  stones: 1,
  map: [
    "############################################",
    "############################################",
    "############################################",
    "##############...........................###",
    "##############................*..........###",
    "##############.....#.....................###",
    "##...........#............#..............###",
    "##...........#..P........................###",
    "##......f....#...........................###",
    "##...........j...................#.......###",
    "##..@......c.j........N................X.###",
    "##...........j...........................###",
    "##...........#...........................###",
    "##...........#...........................###",
    "##...........#.............#........S....###",
    "##############.....#.....................###",
    "##############...........................###",
    "##############...........................###",
    "############################################",
    "############################################",
  ],
  legend: {
    c: { kind: "key", note: 1 },
    j: { kind: "glass", notes: [1, 4] },
    P: { kind: "crystal", note: 4, prism: true },
    N: { kind: "warden", creature: "metronome" },
    S: { kind: "warden" },
    f: {
      kind: "hint",
      text: "The glass wants C and G at once. You have the C. Listen through the glass: something beyond it keeps a beat, and something answers every beat.",
      radius: 1.8,
    },
  },
};

export const THE_CONDUCTOR: LevelDef = {
  id: "the-conductor",
  chapter: "XXI",
  title: "The Conductor",
  tagline: "Three chords, and the one who keeps the Instrument in tune. It hears every wrong note.",
  act: 3,
  abilities: KIT,
  introduces: ["conductor"],
  stones: 2,
  map: [
    "######################################################",
    "######################################################",
    "########################.....#########################",
    "########################..X..#########################",
    "########################.....############...##########",
    "##########################.##############*..x.....M###",
    "##########################.##############...#P.....###",
    "################.....................############..###",
    "####.*.#########...p.............q...############..###",
    "####...#########.....#.........#.....############..###",
    "#####w##########..........K..........#######.......###",
    "##.......#######.....................#######.......###",
    "##........................#........................###",
    "##.......#######.....................#######.......###",
    "##.......#######.....#.........#.....#######...c...###",
    "##...ae..#######...z.............r...#######.......###",
    "##.......#######......................######.......###",
    "##########################.#########..################",
    "##########################.#########..################",
    "#######################t..h...######..####u#....######",
    "#######################.f.....######.......y..*.######",
    "#######################...@...##############....######",
    "#######################.gk..c.########################",
    "######################################################",
    "######################################################",
  ],
  legend: {
    a: { kind: "key", note: 0 },
    c: { kind: "key", note: 1 },
    k: { kind: "key", note: 2 },
    e: { kind: "key", note: 3 },
    g: { kind: "key", note: 4 },
    t: { kind: "tube", pair: "vault" },
    u: { kind: "tube", pair: "vault" },
    w: { kind: "glass", notes: [0, 3] },
    x: { kind: "glass", notes: [1, 4] },
    y: { kind: "glass", notes: [2, 4] },
    P: { kind: "crystal", note: 4, prism: true },
    M: { kind: "mimic" },
    K: { kind: "warden", creature: "conductor", route: "pqrz" },
    p: { kind: "waypoint" },
    q: { kind: "waypoint" },
    r: { kind: "waypoint" },
    z: { kind: "waypoint" },
    h: {
      kind: "hint",
      text: "Three vaults, three chords, and the Gate needs all three shards. What walks the hall above hears every wrong note struck anywhere.",
      radius: 1.6,
    },
    f: { kind: "hint", text: "This tube runs to the south-east vault. A wrong note down it rings out there — far from you.", radius: 1.4 },
  },
};
