import type { LevelDef } from "../level-types";

export const THE_LISTENER: LevelDef = {
  id: "the-listener",
  chapter: "IV",
  title: "The Listener",
  tagline: "It has no eyes. It does not need them.",
  stones: 0,
  map: [
    "####################################",
    "####################################",
    "###......########.....##############",
    "##........#######..*..##############",
    "##..@..s..#######.....##############",
    "##........#######.....##############",
    "###......###..............m.########",
    "#####.######................########",
    "#####.######...##.......##..########",
    "#####.######...##.......##..########",
    "#####.....a..b......V......c....X###",
    "############................########",
    "############...##.......##..########",
    "############...##.......##..########",
    "############.m..............########",
    "############.......,........########",
    "####################################",
    "####################################",
  ],
  legend: {
    V: { kind: "warden", route: "bc" },
    b: { kind: "waypoint" },
    c: { kind: "waypoint" },
    a: {
      kind: "hint",
      text: "Something walks the hall. Hold [Shift] to creep — quiet, but never silent within arm's reach. And creeping is blindness.",
      radius: 1.8,
    },
  },
  startHints: [
    { text: "Pick up stones by walking over them. [Click] to throw — their clatter carries far.", delay: 1.2, duration: 7 },
  ],
};

export const STILL_WATER: LevelDef = {
  id: "still-water",
  chapter: "V",
  title: "Still Water",
  tagline: "Every step in the water is a word spoken aloud.",
  map: [
    "##################################",
    "##################################",
    "##################################",
    "##......~~~~~~~~~~~~.a..##########",
    "##..@...~~~~~~~~~~~~...m##########",
    "##......~~~~~*.~~~~~....##########",
    "##..s...~~~~~..~~~~~..V.##########",
    "##......~~~~~~~~~~~~....1.....X.##",
    "##......~~~~~~~~~~~~.b..##########",
    "########~~~d~~~~~~~~....##########",
    "########~~~~~~~~~~~~..h.##########",
    "########~~~~~~~~~~~~....##########",
    "####################oooo##########",
    "####################oAoo##########",
    "####################oooo##########",
    "##################################",
  ],
  legend: {
    V: { kind: "warden", route: "ab" },
    a: { kind: "waypoint" },
    b: { kind: "waypoint" },
    A: { kind: "bell", group: 1, timed: 6 },
    h: { kind: "hint", text: "This door only listens for a moment. Ring, then run.", radius: 1.6 },
  },
  startHints: [
    { text: "Water betrays every step — even sneaking. Listen for the clicking, and cross when it is far.", delay: 1.4, duration: 7.5 },
  ],
};

export const CHOIR_OF_GLASS: LevelDef = {
  id: "choir-of-glass",
  chapter: "VI",
  title: "Choir of Glass",
  tagline: "Make the stone sing, and the hunters will follow the song.",
  map: [
    "##########################################",
    "##########################################",
    "##########################################",
    "##########################################",
    "##########################################",
    "############....................##########",
    "############.m...............,..##########",
    "############...#.......#........##########",
    "##......####...............W....##########",
    "##......####....................##########",
    "##..@.....a........C............1.....X###",
    "##......####....................##########",
    "##..s...####...............W....##########",
    "############...#.......#........##########",
    "############..d...............A.##########",
    "############f.......P.........g.##########",
    "####################...###################",
    "####################.*.###################",
    "####################...###################",
    "##########################################",
  ],
  legend: {
    A: { kind: "bell", group: 1 },
    P: { kind: "warden", route: "fg" },
    f: { kind: "waypoint" },
    g: { kind: "waypoint" },
    a: {
      kind: "hint",
      text: "Hunters guard the door, and another walks the nave. A resonance crystal sings loud enough for all of them to hear.",
      radius: 1.8,
    },
  },
};

export const DEEP_GATE: LevelDef = {
  id: "deep-gate",
  chapter: "VII",
  title: "The Deep Gate",
  tagline: "Three shards sleep in three wings. Everything you have learned, all at once.",
  endsAct: {
    title: "The Stair Beneath",
    text: "The last gate of the temple does not open onto daylight. It opens onto a stair, and up the stair comes a breath of cold air from somewhere far below. Something down there is breathing. You were never meant to stop listening.",
    next: "Descend further",
  },
  map: [
    "##############################################",
    "##############################################",
    "##############################################",
    "###############.............#........#########",
    "###############..........m..#.....*..#########",
    "###############.............#........#########",
    "##AooooCooooooo.j...........1........#########",
    "###############.............#.....Q..#########",
    "###############.....,.......#........#########",
    "###############.............#.r......#########",
    "##################.###########################",
    "###ooooo.oooo#####.##############.g.......h.##",
    "###ooooo.oooo#####.##############.....V.....##",
    "###oo.o....oo#####..........#####~~~~~~~~~~~##",
    "###o*.o.oo.oo####.....X......####~~~~~~~~~~~##",
    "###o.oo.oo.oo####..#......#..####~~~~~~...~~##",
    "###o.oo.oo...,........k..........~~~~~~.*.~~##",
    "###o.oo.oo.oo####............####~~~~~~...~~##",
    "###o....oo.oo####.....@.s....####~~~~~~~~~~~##",
    "###oooooo..oo#####..........#####~~~d~~~~~~~##",
    "###oooooooooo####################~~~~~~~~~~~##",
    "###oooooooooo####################~~~~~~~~~~~##",
    "##############################################",
    "##############################################",
  ],
  legend: {
    A: { kind: "bell", group: 1 },
    V: { kind: "warden", route: "gh" },
    Q: { kind: "warden", route: "r" },
    r: { kind: "waypoint" },
    g: { kind: "waypoint" },
    h: { kind: "waypoint" },
    j: { kind: "hint", text: "No voice reaches that far. A crystal might.", radius: 1.8 },
    k: { kind: "hint", text: "West, north and east: one shard in each wing. The Gate waits for all three.", radius: 1.4 },
  },
};
