import type { LevelDef } from "../level-types";

export const THE_WATCHER: LevelDef = {
  id: "the-watcher",
  chapter: "XI",
  title: "The Watcher",
  tagline: "It never moves. It never sleeps. It only ever listens.",
  act: 2,
  abilities: ["deepListen", "focus"],
  map: [
    "##############################################",
    "##############################################",
    "##############################################",
    "##############################################",
    "####################################.......###",
    "####################################.......###",
    "##########.V.....................p......X..###",
    "##########.................................###",
    "##########.....Y.ooooooooooo.......#.......###",
    "##########..oo...ooooooooooo..oo...#.......###",
    "##########..oo...ooooooooooo..oo...###########",
    "##########^^.....ooo.....ooo.......###########",
    "##########^^........*..S.ooom....*.###########",
    "##########^^.....ooo.....ooo.......###########",
    "##########..oo...ooooooooooo..oo...###########",
    "##.......#..oo...ooooooooooo..oo...###########",
    "##.......#.....r.ooooooooooo.......###########",
    "##.......a.........................###########",
    "##..@......q.....................U.###########",
    "##.....s.#####################################",
    "##.......#####################################",
    "##############################################",
    "##############################################",
    "##############################################",
  ],
  legend: {
    S: { kind: "warden", creature: "sentinel" },
    V: { kind: "warden", route: "p" },
    U: { kind: "warden", route: "q" },
    Y: { kind: "warden", route: "r" },
    p: { kind: "waypoint" },
    q: { kind: "waypoint" },
    r: { kind: "waypoint" },
    a: {
      kind: "hint",
      text: "The Watcher calls out on its own, and its voice lights the hall. Borrow its light. If it hears yours, it screams for the hunters.",
      radius: 1.8,
    },
  },
};

export const CHOIR_OF_MANY: LevelDef = {
  id: "choir-of-many",
  chapter: "XII",
  title: "Choir of Many",
  tagline: "They hunt as one. Wake one, and you have woken them all.",
  act: 2,
  abilities: ["deepListen", "focus", "lureStone"],
  grants: ["lureStone"],
  stones: 1,
  map: [
    "##############################################",
    "##############################################",
    "##############################################",
    "#########.........................############",
    "#########...N...*.............n.A.############",
    "#########.........................############",
    "#########....##....##....##.......############",
    "#########....##....##....##.......############",
    "##......#.........................############",
    "##......#.........................############",
    "##..@.............................############",
    "##.......a...##....##....##.......#.......####",
    "##...s..#....##....##....##....H..#.......####",
    "##......#.........................1....X..####",
    "#########.......................K.1.......####",
    "#########..d.............b.....J..#.......####",
    "#########.........................#.......####",
    "###########################.......############",
    "###########################:::::::############",
    "###########################:::::m:############",
    "###########################::::::*############",
    "##############################################",
    "##############################################",
    "##############################################",
  ],
  legend: {
    H: { kind: "warden", creature: "chorus" },
    J: { kind: "warden", creature: "chorus" },
    K: { kind: "warden", creature: "chorus" },
    N: { kind: "warden", creature: "chorus", route: "n" },
    n: { kind: "waypoint" },
    A: { kind: "bell", group: 1, timed: 10 },
    a: { kind: "hint", text: "Three of them stand before the door. When one hears you, all of them come.", radius: 1.8 },
    b: { kind: "hint", text: "The loft below is deep in silt. Nothing falls there with a sound — nor walks there with one.", radius: 1.8 },
  },
};

export const THE_PATIENT_ONE: LevelDef = {
  id: "the-patient-one",
  chapter: "XIII",
  title: "The Patient One",
  tagline: "Here the dark goes on forever, and the things in it are in no hurry at all.",
  act: 2,
  abilities: ["deepListen", "focus", "lureStone", "muffle"],
  grants: ["muffle"],
  stones: 1,
  map: [
    "################################################",
    "#oooooooooooooooooooooooooooooooooooooooooooooo#",
    "#oooooooooooooooooooooooooooooooooooooooooooooo#",
    "#oooooooooooooooooooooooooooooooooooooooooooooo#",
    "#ooooooooooooooooo..............ooooooooooooooo#",
    "#ooooooooooooooooo...m.......*..ooooooooooooooo#",
    "#ooooooooooooooooo..P.........a.ooooooooooooooo#",
    "#o......oooooooooo........oo....ooooooooooooooo#",
    "#o......oooooooooo........oo....ooooooo......oo#",
    "#o......oooooooooo..............ooooooo......oo#",
    "#o..@..h........T....................U....X..oo#",
    "#o.................k.........................oo#",
    "#o.s....oooooooooo....oo........ooooooo......oo#",
    "#o......oooooooooo....oo........ooooooo......oo#",
    "#ooooooooooooooooo..............ooooooooooooooo#",
    "#ooooooooooooooooo..b.........Q.ooooooooooooooo#",
    "#ooooooooooooooooo......oo....d.ooooooooooooooo#",
    "#ooooooooooooooooo.*....oo......ooooooooooooooo#",
    "#oooooooooooooooooooooooooooooooooooooooooooooo#",
    "#oooooooooooooooooooooooooooooooooooooooooooooo#",
    "#oooooooooooooooooooooooooooooooooooooooooooooo#",
    "################################################",
  ],
  legend: {
    T: { kind: "warden", creature: "tremor" },
    U: { kind: "warden", creature: "tremor" },
    P: { kind: "warden", creature: "stalker", route: "a" },
    Q: { kind: "warden", creature: "stalker", route: "b" },
    a: { kind: "waypoint" },
    b: { kind: "waypoint" },
    h: {
      kind: "hint",
      text: "Something heavy sits where the bridge meets the rock. It will feel even your softest step. Press [F], then walk — quickly.",
      radius: 1.6,
    },
    k: { kind: "hint", text: "The patient ones never give up on a sound. Stay silent, and let their clicking show you where they walk.", radius: 1.8 },
  },
};

export const WHERE_THE_DARK_BREATHES: LevelDef = {
  id: "where-the-dark-breathes",
  chapter: "XIV",
  title: "Where the Dark Breathes",
  tagline: "Every sound you have ever made was carried here. Three shards, and the last Gate.",
  act: 2,
  abilities: ["deepListen", "focus", "lureStone", "muffle"],
  stones: 1,
  map: [
    "############################################################",
    "########################################.d.###....##########",
    "##################oooooooo...###########...###.*..##########",
    "##################oooooooo.A.#...............#....##########",
    "#######::...:::###oooooooo...#.Y...........y.#%%%%##########",
    "#######::.e.:Z:###ooooooooooo#...............#............##",
    "#######::...:::###ooooooooooo#.............*.#.K........k.##",
    "#######::...:::###ooooooooooo#...............#............##",
    "#######::...:::###oooooooo...#...ooooooo.....#............##",
    "#######::...:::...oooooooo.R.#...ooooooo.....#............##",
    "##.....::...:::...oooooooo...#...oo...oo.....#............##",
    "##.....::...:::...ooooooooooo#...oo.S.oo.....%.........H..##",
    "##.@..a::.T.:::.b.ooooooooooo#...oo...oo.....%.g........X.##",
    "##.....::...:::...ooooooooooo#...ooooooo.....#............##",
    "##...s.::...:::...ooooooooooo#oo.ooooooo.....#.........J..##",
    "##.....::...:::...ooooooooooo#oo.............#............##",
    "#######::...:::...ooooooooooo#m..............#............##",
    "#######::...:z:...ooooooooooo#...............#............##",
    "#######::...:::........1.......c.............####::::::#####",
    "#######::...:::###ooooooooooo>>>>>>>>>>>>>>>>####:::d::#####",
    "#######::.f.~~~###ooooooooooo>>>>>&>>>>>>>>>>####::::::#####",
    "#######::...~*~###ooooooooooo#...............#####::::######",
    "#####################################....###################",
    "#####################################..W.###################",
    "############################################################",
  ],
  legend: {
    T: { kind: "warden", creature: "tremor", route: "ef" },
    Z: { kind: "warden", creature: "tremor", route: "z" },
    e: { kind: "waypoint" },
    f: { kind: "waypoint" },
    z: { kind: "waypoint" },
    R: { kind: "resonator", facing: "n" },
    A: { kind: "bell", group: 1 },
    S: { kind: "warden", creature: "sentinel" },
    Y: { kind: "warden", route: "y" },
    y: { kind: "waypoint" },
    H: { kind: "warden", creature: "chorus" },
    J: { kind: "warden", creature: "chorus" },
    K: { kind: "warden", creature: "chorus", route: "k" },
    k: { kind: "waypoint" },
    a: { kind: "hint", text: "It walks the stone lane. Keep to the silt, and cross only when it is far — or cross in silence.", radius: 1.6 },
    b: {
      kind: "hint",
      text: "The bell across the chasm is beyond any voice. The dish between might carry one — if it faces the right way.",
      radius: 1.8,
    },
    c: { kind: "hint", text: "The chime sings whenever the wind moves it. Let it light the hall — and keep clear of what it wakes.", radius: 1.8 },
    g: { kind: "hint", text: "Behind the moss, no sound escapes — and none comes in. Two voices guard the last Gate.", radius: 1.6 },
  },
};
