import type { Ability, LevelDef } from "../level-types";

/** Act III keeps the whole kit of Act II. */
const KIT: readonly Ability[] = ["deepListen", "focus", "lureStone", "muffle"];

export const THE_TUNING_HALL: LevelDef = {
  id: "the-tuning-hall",
  chapter: "XV",
  title: "The Tuning Hall",
  tagline: "Every stone here was cut to sing one note. Find the one that answers.",
  act: 3,
  abilities: KIT,
  introduces: ["tones", "glass"],
  stones: 1,
  map: [
    "##############################################",
    "###################.*.##############.X.#######",
    "###################...##############...#######",
    "###################nnn##############jjj#######",
    "###############...........................####",
    "##.......######...........................####",
    "##.......######......k...............G....####",
    "##..@....######...........................####",
    "##.......######...........................####",
    "##.......h..b.....V................q......####",
    "##.......######...........................####",
    "##.a.c.e.######.........U.................####",
    "##.......######...........................####",
    "##############...........a.g.f............####",
    "###############...........................####",
    "##############################################",
  ],
  legend: {
    a: { kind: "key", note: 0 },
    c: { kind: "key", note: 1 },
    k: { kind: "key", note: 2 },
    e: { kind: "key", note: 3 },
    g: { kind: "key", note: 4 },
    h: { kind: "glass", notes: [3] },
    n: { kind: "glass", notes: [2] },
    j: { kind: "glass", notes: [4] },
    G: { kind: "crystal", note: 4 },
    U: { kind: "crystal", note: 0 },
    V: { kind: "warden", route: "q" },
    q: { kind: "waypoint" },
    b: {
      kind: "hint",
      text: "Something walks the hall, back and forth. A call carries far — a focused one [Q] only where you aim it.",
      radius: 1.6,
    },
    f: { kind: "hint", text: "No voice reaches the Gate's glass from here. A crystal tuned to its note might.", radius: 2 },
  },
};

export const ECHO_OF_AN_ECHO: LevelDef = {
  id: "echo-of-an-echo",
  chapter: "XVI",
  title: "Echo of an Echo",
  tagline: "Some voices carry through stone. Some wait, and say it again.",
  act: 3,
  abilities: KIT,
  introduces: ["tubes", "mimic"],
  stones: 1,
  map: [
    "################################################",
    "#######################################....#####",
    "#################################.M...j..X.#####",
    "#################################.....j....#####",
    "#################################..####....#####",
    "#################################..#############",
    "#################################..#############",
    "#################################..#############",
    "#########################................#######",
    "##........##########.*.##...........S....#######",
    "##......p.##########...##................#######",
    "##..@.....###########k###.....f..........#######",
    "##..........b...........h................#######",
    "##........############q##....e...........#######",
    "##.a.c....###############................#######",
    "##........###############................#######",
    "#########################................#######",
    "#########################................#######",
    "################################################",
    "################################################",
  ],
  legend: {
    a: { kind: "key", note: 0 },
    c: { kind: "key", note: 1 },
    e: { kind: "key", note: 3 },
    p: { kind: "tube", pair: "long" },
    q: { kind: "tube", pair: "long" },
    h: { kind: "glass", notes: [1] },
    k: { kind: "glass", notes: [0] },
    j: { kind: "glass", notes: [3] },
    M: { kind: "mimic" },
    S: { kind: "warden" },
    b: { kind: "hint", text: "Two panes wait at the far end, and no voice carries that far. The bronze mouth by the keys might.", radius: 1.6 },
    f: { kind: "hint", text: "The Gate's glass is round a corner no call can turn. Something at the bend is listening.", radius: 1.8 },
  },
};

export const THE_TURNING_DISHES: LevelDef = {
  id: "the-turning-dishes",
  chapter: "XVII",
  title: "The Turning Dishes",
  tagline: "The old dishes still sing, each the one way it faces. Teach them where to look.",
  act: 3,
  abilities: KIT,
  introduces: ["dishes"],
  stones: 1,
  map: [
    "##############################################",
    "##########.#####.#####.#####.###########....##",
    "##..........V................u.....f...j..X.##",
    "###.###########################ooooooooo######",
    "###.################oooooooooooooooooooooo####",
    "##..................oooooooooooooooooooooo####",
    "##..................oooooooooooooooooooooo####",
    "##..............b...oooooooooooooooooooooo####",
    "##..................oooooooooooooooooooooo####",
    "##...@.............gooooooooRoooooooooQooo####",
    "##..................oooooooooooooooooooooo####",
    "##..................oooooooooooooooooooooo####",
    "##..................oooooooooooooooooooooo####",
    "##..................oooooooooooooooooooooo####",
    "##..................oooooooooooooooooooooo####",
    "####################oooooooooooooooooooooo####",
    "##############################################",
  ],
  legend: {
    g: { kind: "key", note: 4 },
    R: { kind: "crystal", note: 4, facing: "n", turnable: true },
    Q: { kind: "crystal", note: 4, facing: "s", turnable: true },
    j: { kind: "glass", notes: [4] },
    V: { kind: "warden", route: "u" },
    u: { kind: "waypoint" },
    b: {
      kind: "hint",
      text: "Two dishes stand in the chasm, tuned to G, facing nowhere useful. A focused call turns a dish a quarter step; any other sound makes it sing.",
      radius: 1.8,
    },
    f: { kind: "hint", text: "The Gate's glass is right above the far dish. Something walks this ledge — the alcoves are deep enough to let it pass.", radius: 1.4 },
  },
};

export const CHORD: LevelDef = {
  id: "chord",
  chapter: "XVIII",
  title: "Chord",
  tagline: "Some doors listen for more than one voice at once.",
  act: 3,
  abilities: KIT,
  introduces: ["chords"],
  stones: 1,
  map: [
    "################################################",
    "############################.X.#################",
    "############################...#################",
    "############################jjj###########....##",
    "#################........................#..*.##",
    "#################......Q..........P....R.#....##",
    "#################........................k....##",
    "#################..V..................uT.#....##",
    "##........#######............c...........#....##",
    "##........#######........................#....##",
    "##..@.....#######........................#######",
    "##........h...b..........................#######",
    "##........#######...................c....#######",
    "##...cae..#######.............e..........#######",
    "##........#######........................#######",
    "#################........................#######",
    "#################........................#######",
    "################################################",
    "################################################",
  ],
  legend: {
    a: { kind: "key", note: 0 },
    c: { kind: "key", note: 1 },
    e: { kind: "key", note: 3 },
    h: { kind: "glass", notes: [0, 3] },
    j: { kind: "glass", notes: [1, 4] },
    // Thick glass: only a voice right beside it is strong enough.
    k: { kind: "glass", notes: [3, 4], threshold: 0.8 },
    P: { kind: "crystal", note: 4, prism: true },
    R: { kind: "crystal", note: 4, prism: true },
    Q: { kind: "crystal", note: 2, prism: true },
    T: { kind: "crystal", note: 3 },
    V: { kind: "warden", route: "u" },
    u: { kind: "waypoint" },
    b: {
      kind: "hint",
      text: "Prisms wake to anything and always sing their own note — the right one, or the wrong one. Mind which ones your voice can reach.",
      radius: 1.6,
    },
  },
};
